'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Minion_One.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aiuto_novita_mo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aiuto.novita.mo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aiuto_primoavvio_mo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aiuto.primoavvio.mo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aiuto_tutorial_mo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aiuto.tutorial.mo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property altremodalita_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("altremodalita.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property altremodalita1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("altremodalita1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property attenzione_errore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attenzione.errore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property attenzione_errore22x22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attenzione.errore22x22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aumenta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aumenta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property centro_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("centro.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chiudi_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chiudi_finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property continua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property continuadoppia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuadoppia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property destra_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("destra.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property destra_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("destra.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property destrasopra_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("destrasopra.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property destrasotto_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("destrasotto.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EspandiComboBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EspandiComboBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property giustificato_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("giustificato.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property immcar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("immcar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property immerr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("immerr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impostazioni_cella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impostazioni.cella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impostazioniautosavemo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impostazioniautosavemo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impostazioniavanzatemo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impostazioniavanzatemo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impostazionigeneralemo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impostazionigeneralemo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impostazioniinterfacciamo4_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impostazioniinterfacciamo4.3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impostazioniprivacymo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impostazioniprivacymo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inferiore_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inferiore.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ingrandisci_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ingrandisci_finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property middle_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("middle.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOne19x19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOne19x19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOneLogoNEW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOneLogoNEW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOneLogoNEW2white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOneLogoNEW2white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOneNEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOneNEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOneNEW_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOneNEW-16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinionOneNEW_50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinionOneNEW-50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nascondialtremodalita_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nascondialtremodalita.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property niente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("niente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nonnumerato_elenco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nonnumerato.elenco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property numerato_elenco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("numerato.elenco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punteggiata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punteggiata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Riduci() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Riduci", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property riduciaicona_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("riduciaicona_finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ripristina_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ripristina_finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property si() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("si", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sinistra_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinistra.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sinistra_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinistra.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sinistrasopra_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinistrasopra.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sinistrasotto_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinistrasotto.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sopra_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sopra.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sotto_finestra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sotto.finestra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superiore_posizione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superiore.posizione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superiore1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superiore1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trasparente105x31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trasparente105x31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tratteggiata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tratteggiata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
